- assets/desktop-slider.css
- assets/mobile-slider.css
- sections/desktop-slider.liquid
- snippets/product-slider.liquid
- snippets/slider.liquid
- styles/desktop-slider.scss
- styles/mobile-slider.scss
- templates/index.json
[YSHOP2-167](https://youcanshop.atlassian.net/browse/YSHOP2-167)
[YSHOP2-167]: https://youcanshop.atlassian.net/browse/YSHOP2-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-167: As a seller, I would like to be able to add one or more slider images

- sections/multi-column.liquid
- templates/index.json
[YSHOP2-168](https://youcanshop.atlassian.net/browse/YSHOP2-168)
[YSHOP2-168]: https://youcanshop.atlassian.net/browse/YSHOP2-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-168: As a seller, I would like to be able to add multiple columns

- assets/countdown.css
- assets/featured-products.css
- assets/helper.js
- assets/main.css
- assets/mobile-slider.css
- assets/product-slider.css
- sections/featured-product-slider.liquid
- snippets/countdown.liquid
- snippets/product-slider.liquid
- styles/countdown.scss
- styles/featured-products.scss
- styles/main.scss
- styles/mobile-slider.scss
- styles/product-slider.scss
- templates/index.json
[YSHOP2-171](https://youcanshop.atlassian.net/browse/YSHOP2-171)
[YSHOP2-171]: https://youcanshop.atlassian.net/browse/YSHOP2-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-171: As a seller, I want to be able to add a slider of products

- assets/reviews.css
- assets/reviews.js
- locales/ar.default.json
- sections/product-reviews.liquid
- snippets/reviews.liquid
- styles/reviews.scss
- templates/index.json
[DYSHOP2-195](https://youcanshop.atlassian.net/browse/YSHOP2-195)
> DYSHOP2-195: As a seller, I want to be able to add customer reviews

- assets/main.css
- assets/product.css
- assets/product.js
- locales/ar.default.json
- sections/product.liquid
- snippets/product-variants.liquid
- styles/main.scss
- styles/product.scss
[YSHOP2-228](https://youcanshop.atlassian.net/browse/YSHOP2-228)
[YSHOP2-228]: https://youcanshop.atlassian.net/browse/YSHOP2-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-228 : COD theme v3 > As a seller, I want to be able to add the product variants (uploading image, image button)

- assets/dropdown-menu.js
- assets/main.css
- assets/product-listing.css
- assets/product.js
- assets/queries-handler.js
- snippets/main-sort.liquid
- snippets/product-variants.liquid
- snippets/reviews.liquid
- styles/main.scss
- styles/product-listing.scss
[YSHOP2-230](https://youcanshop.atlassian.net/browse/YSHOP2-230)
[YSHOP2-230]: https://youcanshop.atlassian.net/browse/YSHOP2-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-230 : COD theme v3 > As a seller, I want to be able to add the product variants (dropdown menu, radio button)

- assets/collection-listing.css
- assets/main.css
- assets/product-listing.css
- assets/queries-handler.css
- locales/ar.default.json
- sections/main-collection.liquid
- sections/product.liquid
- snippets/main-pagination.liquid
- snippets/main-sort.liquid
- snippets/product-preview.liquid
- snippets/reviews.liquid
- styles/collection-listing.scss
- styles/main.scss
- styles/product-listing.scss
- styles/queries-handler.scss
- templates/index.json
[DOT-YSHOP2-231](https://youcanshop.atlassian.net/browse/YSHOP2-231)
> YSHOP2-231: As a seller, I would like to be able to add the list of products in a category with a pagination

- assets/cart.css
- assets/featured-products.css
- assets/main.css
- locales/ar.default.json
- locales/en.json
- locales/fr.json
- sections/main-cart.liquid
- snippets/product-preview.liquid
- styles/cart.scss
- styles/featured-products.scss
- styles/main.scss
- templates/index.json
[YSHOP2-211](https://youcanshop.atlassian.net/browse/YSHOP2-211)
[YSHOP2-211]: https://youcanshop.atlassian.net/browse/YSHOP2-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-211: As a buyer, I want to be able to see a recap of my cart items

- assets/main.css
- assets/product.css
- assets/product.js
- snippets/add-to-cart.liquid
- snippets/single-product.liquid
- styles/main.scss
- styles/product.scss
- templates/product.json
[YSHOP2-178](https://youcanshop.atlassian.net/browse/YSHOP2-178)
[YSHOP2-178]: https://youcanshop.atlassian.net/browse/YSHOP2-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-178 : As a seller, I want to be able to add an 'add to cart button'

- assets/main.css
- assets/product-column.css
- assets/product.css
- sections/product.liquid
- snippets/product-quantity-input.liquid
- snippets/product-variants.liquid
- snippets/single-product.liquid
- styles/main.scss
- styles/product-column.scss
- styles/product.scss
[YSHOP2-271](https://youcanshop.atlassian.net/browse/YSHOP2-271)
[YSHOP2-271]: https://youcanshop.atlassian.net/browse/YSHOP2-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-271 : As a seller, I want to be able to add countdown

- sections/product-column.liquid
- sections/product.liquid
- snippets/head-config.liquid
- snippets/product-home.liquid
- snippets/single-product.liquid
- templates/index.json
[YSHOP2-273](https://youcanshop.atlassian.net/browse/YSHOP2-273)
[YSHOP2-273]: https://youcanshop.atlassian.net/browse/YSHOP2-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-273: As a seller, I would like to be able to add a single product section to the home page

- assets/main.js
- assets/navbar.css
- assets/product-listing.css
- locales/ar.default.json
- sections/main-navbar.liquid
- sections/main-search.liquid
- styles/navbar.scss
- styles/product-listing.scss
[YSHOP2-213](https://youcanshop.atlassian.net/browse/YSHOP2-213)
[YSHOP2-213]: https://youcanshop.atlassian.net/browse/YSHOP2-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-213: As a seller, I would like to be able to add the list of searchable products in one page

- assets/featured-products.css
- assets/product-listing.css
- styles/featured-products.scss
- styles/product-listing.scss
[DOT-X](https://youcanshop.atlassian.net/browse/DOT-X)
> Fix the product page button display

- assets/accordion.css
- assets/main.css
- assets/product.css
- sections/product.liquid
- snippets/accordion.liquid
- snippets/single-product.liquid
- styles/accordion.scss
- styles/main.scss
- styles/product.scss
[YSHOP2-283](https://youcanshop.atlassian.net/browse/YSHOP2-283)
breadcrumb will be added in another PR
[YSHOP2-283]: https://youcanshop.atlassian.net/browse/YSHOP2-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-283 : Update styling for some blocks in the single product section

- assets/add-to-cart.js
- assets/cart-drawer.css
- snippets/cart-drawer.liquid
- styles/cart-drawer.scss
> Fix undefined total price

- assets/featured-collections.css
- sections/featured-collections.liquid
- styles/featured-collections.scss
> Dark fix the featured collection scroll

- assets/reviews-count.js
- sections/product.liquid
- snippets/product-home.liquid
> DARK : fix reviews in home page and product page

- assets/main.js
- assets/navbar.css
- sections/main-list-collections.liquid
- snippets/collection-preview.liquid
- styles/navbar.scss
- templates/list-collections.json
[YSHOP2-282](https://youcanshop.atlassian.net/browse/YSHOP2-282)
[YSHOP2-174]: https://youcanshop.atlassian.net/browse/YSHOP2-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-282]: https://youcanshop.atlassian.net/browse/YSHOP2-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-282: Add color settings on the featured collections

- .github/pull_request_template.md
- assets/video.css
- sections/main-video.liquid
- styles/video.scss
[YSHOP2-281](https://youcanshop.atlassian.net/browse/YSHOP2-281)
[YSHOP2-300]: https://youcanshop.atlassian.net/browse/YSHOP2-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-281]: https://youcanshop.atlassian.net/browse/YSHOP2-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-300: No bottom padding for the Video section

- assets/cart-drawer.css
- assets/main.css
- assets/navbar.css
- assets/product-listing.css
- assets/product-slider.css
- snippets/express-checkout.liquid
- styles/cart-drawer.scss
- styles/cart.scss
- styles/main.scss
- styles/navbar.scss
- styles/product-listing.scss
- styles/product-slider.scss
[YSHOP2-320](https://youcanshop.atlassian.net/browse/YSHOP2-320)
[YSHOP2-320]: https://youcanshop.atlassian.net/browse/YSHOP2-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-320 : Fix LTR direction styling bugs

- sections/multi-column.liquid
[YSHOP2-333](https://youcanshop.atlassian.net/browse/YSHOP2-333)
[YSHOP2-332](https://youcanshop.atlassian.net/browse/YSHOP2-332)
[YSHOP2-333]: https://youcanshop.atlassian.net/browse/YSHOP2-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[YSHOP2-332]: https://youcanshop.atlassian.net/browse/YSHOP2-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-333: Multicolumn (Theme 3) > Title position setting not applied

- assets/express-checkout.js
- snippets/express-checkout.liquid
[YSHOP2-335](https://youcanshop.atlassian.net/browse/YSHOP2-335)
I have only fix the custom input 
[YSHOP2-335]: https://youcanshop.atlassian.net/browse/YSHOP2-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-335 :  COD v3 > Express checkout bloc - Gap between input fields settings not working

- sections/featured-product-slider.liquid
> DARK: Remove fade transition settings, since it's not support perPage option

- snippets/product-home.liquid
> DARK : COD V3 > Product column section > fix compare price value error

- sections/product.liquid
[YSHOP2-354](https://youcanshop.atlassian.net/browse/YSHOP2-354)
In this PR I only set the limit and I didn't change the styling for the buttons in the sticky mode because the element are not inline 
[YSHOP2-354]: https://youcanshop.atlassian.net/browse/YSHOP2-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-354 : Single product > Add to card size is small 

- assets/stock.css
- sections/product.liquid
- snippets/single-product.liquid
- snippets/stock.liquid
- styles/stock.scss
[YSHOP2-356](https://youcanshop.atlassian.net/browse/YSHOP2-356)
[YSHOP2-356]: https://youcanshop.atlassian.net/browse/YSHOP2-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-356 : Single product > Stock > set default limit value

- sections/desktop-slider.liquid
[YSHOP2-306](https://youcanshop.atlassian.net/browse/YSHOP2-306)
[YSHOP2-306]: https://youcanshop.atlassian.net/browse/YSHOP2-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-306: [Slider] On Overlay Background Color change, keep the transparency level previously selected

- assets/helper.js
[YSHOP2-500](https://youcanshop.atlassian.net/browse/YSHOP2-500)
[YSHOP2-500]: https://youcanshop.atlassian.net/browse/YSHOP2-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-500 : COD V3 > Countdown functionality triggering an infinite loop making the web page crush

- assets/reviews-count.js
- assets/reviews.js
- package.json
- sections/product-reviews.liquid
- sections/product.liquid
- snippets/head-config.liquid
- snippets/product-home.liquid
- snippets/reviews.liquid
[YSHOP2-175](https://youcanshop.atlassian.net/browse/YSHOP2-175)
[YSHOP2-175]: https://youcanshop.atlassian.net/browse/YSHOP2-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-175 : As a seller, I want to be able to add ratings of the product

- assets/featured-products.css
- styles/featured-products.scss
[YSHOP2-521](https://youcanshop.atlassian.net/browse/YSHOP2-521)
-  [ ] Go to homepage and scroll to `Featured products by category`
-  [ ] Displayed images should be displayed properly
[YSHOP2-521]: https://youcanshop.atlassian.net/browse/YSHOP2-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-521: COD-Theme 3 > Featured products by category > Stretched images

- assets/navbar.css
- styles/navbar.scss
[YSHOP2-518](https://youcanshop.atlassian.net/browse/YSHOP2-518)
-  [ ] Have navbar be sticky.
-  [ ] Set a height for the notice bar that is slower than the height of the nav bar.
-  [ ] Go to the homepage and scroll slightly where the notice bar will only be half visible. 
-  [ ] Click on the search button, the search box should not be offset from the screen.
[YSHOP2-518]: https://youcanshop.atlassian.net/browse/YSHOP2-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-518: COD V3 > Search bar > UI bug

- assets/helper.js
[YSHOP2-526](https://youcanshop.atlassian.net/browse/YSHOP2-526)
[YSHOP2-526]: https://youcanshop.atlassian.net/browse/YSHOP2-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-526 : COD V3 > countdown > The countdown goes negative when date is surpassed instead of going to 0

- sections/main-navbar.liquid
- snippets/head-config.liquid
[SHOP2-510](https://youcanshop.atlassian.net/browse/SHOP2-510)
> YSHOP2-510: Setting: Cart badge color is not working

- sections/main-navbar.liquid
- snippets/head-config.liquid
[YSHOP2-513](https://youcanshop.atlassian.net/browse/YSHOP2-513)
[YSHOP2-513]: https://youcanshop.atlassian.net/browse/YSHOP2-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-513: Navbar shadow not working, to remove.

- sections/featured-product-slider.liquid
… view
[YSHOP2-528](https://youcanshop.atlassian.net/browse/YSHOP2-528)
[YSHOP2-528]: https://youcanshop.atlassian.net/browse/YSHOP2-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-528: If we only have 1 product block, we display 2 products in mobile view

- assets/product-slider.css
- snippets/product-slider.liquid
- styles/product-slider.scss
[YSHOP2-529](https://youcanshop.atlassian.net/browse/YSHOP2-529)
[YSHOP2-529]: https://youcanshop.atlassian.net/browse/YSHOP2-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-529: On the desktop if we only have 1 product block it looks large, and takes the size of the entire container.

- assets/navbar.css
- styles/navbar.scss
> DARK: search box center

- assets/main.js
- assets/navbar.css
- styles/navbar.scss
[YSHOP2-538](https://youcanshop.atlassian.net/browse/YSHOP2-538)
[YSHOP2-538]: https://youcanshop.atlassian.net/browse/YSHOP2-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-538: Conflict when showing both express checkout block and sticky navbar

- sections/desktop-slider.liquid
- templates/index.json
[YSHOP2-520](https://youcanshop.atlassian.net/browse/YSHOP2-520)
[YSHOP2-520]: https://youcanshop.atlassian.net/browse/YSHOP2-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-520 : COD V3 > Slider > UI bugs

- assets/product.css
- snippets/single-product.liquid
- styles/product.scss
[YSHOP2-542](https://youcanshop.atlassian.net/browse/YSHOP2-542)
[YSHOP2-542]: https://youcanshop.atlassian.net/browse/YSHOP2-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-542: The express checkout box shadow is intersected with the description.

- assets/product.css
- styles/product.scss
[YSHOP2-541](https://youcanshop.atlassian.net/browse/YSHOP2-541)
[YSHOP2-541]: https://youcanshop.atlassian.net/browse/YSHOP2-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-541: Product image box is not sticky.

- sections/desktop-slider.liquid
- sections/featured-product-slider.liquid
- styles/countdown.scss
> DARK : fix product slider  bugs

- assets/product.css
- snippets/single-product.liquid
- styles/product.scss
[YSHOP2-537](https://youcanshop.atlassian.net/browse/YSHOP2-537)
[YSHOP2-537]: https://youcanshop.atlassian.net/browse/YSHOP2-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-537: Conflict when showing both express checkout and add to cart blocks

- sections/featured-product-slider.liquid
- sections/featured-products.liquid
- sections/multi-column.liquid
- templates/index.json
[YSHOP2-595](https://youcanshop.atlassian.net/browse/YSHOP2-595)
[YSHOP2-595]: https://youcanshop.atlassian.net/browse/YSHOP2-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-595 : COD v3 > Default text colors for themes

- assets/sticky-checkout.css
- sections/feature-products-by-category.liquid
- snippets/single-product.liquid
- snippets/sticky-checkout.liquid
- styles/sticky-checkout.scss
[YSHOP2-618](https://youcanshop.atlassian.net/browse/YSHOP2-618
[YSHOP2-618]: https://youcanshop.atlassian.net/browse/YSHOP2-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-618: Display the price in the sticky checkout 

- sections/feature-products-by-category.liquid
- sections/featured-collections.liquid
- sections/featured-product-slider.liquid
- sections/featured-products.liquid
[YSHOP2-609](https://youcanshop.atlassian.net/browse/YSHOP2-609)
[YSHOP2-609]: https://youcanshop.atlassian.net/browse/YSHOP2-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-609: As a seller, I should be guided on the images sizes

- sections/desktop-slider.liquid
- snippets/slider.liquid
[YSHOP2-608](https://youcanshop.atlassian.net/browse/YSHOP2-608)
[YSHOP2-608]: https://youcanshop.atlassian.net/browse/YSHOP2-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-608 : COD v3 > Slider - Remove arrows when one image is used

- assets/countdown.css
- assets/helper.js
- snippets/countdown.liquid
- styles/countdown.scss
[YSHOP2-642](https://youcanshop.atlassian.net/browse/YSHOP2-642)
[YSHOP2-642]: https://youcanshop.atlassian.net/browse/YSHOP2-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-642 : Theme 3 -  Products Slider: Adding the full countdown

- assets/product.css
- assets/product.js
- snippets/product-variants.liquid
- styles/product.scss
[YSHOP2-682](https://youcanshop.atlassian.net/browse/YSHOP2-682)
[YSHOP2-682]: https://youcanshop.atlassian.net/browse/YSHOP2-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-682 : COD themes > The price isn't updated when the variants are radio buttons 

- assets/product.css
- sections/notice-bar.liquid
- styles/product.scss
[YSHOP2-711](https://youcanshop.atlassian.net/browse/YSHOP2-711)
[YSHOP2-711]: https://youcanshop.atlassian.net/browse/YSHOP2-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-711: Themes Bugs

- assets/desktop-slider.css
- assets/mobile-slider.css
- sections/desktop-slider.liquid
- styles/desktop-slider.scss
- styles/mobile-slider.scss
[YSHOP2-712](https://youcanshop.atlassian.net/browse/YSHOP2-712)
[YSHOP2-712]: https://youcanshop.atlassian.net/browse/YSHOP2-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-712: Themes - A few settings to add

- assets/add-to-cart.js
- assets/cart-drawer.css
- assets/cart.css
- assets/cart.js
- assets/helper.js
- assets/main.js
- sections/main-cart.liquid
- styles/cart-drawer.scss
- styles/cart.scss
[YSHOP2-693](https://youcanshop.atlassian.net/browse/YSHOP2-693)
[YSHOP2-693]: https://youcanshop.atlassian.net/browse/YSHOP2-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-693 : COD theme V3 > cart page & cart drawer bugs

- config/settings_schema.json
[YSHOP2-701](https://youcanshop.atlassian.net/browse/YSHOP2-701)
[YSHOP2-701]: https://youcanshop.atlassian.net/browse/YSHOP2-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-701 : Adding text on customizing the checkout color in the global settings - theme 3

- assets/add-to-cart.js
- assets/helper.js
- sections/main-navbar.liquid
[YSHOP2-726](https://youcanshop.atlassian.net/browse/YSHOP2-726)
[YSHOP2-726]: https://youcanshop.atlassian.net/browse/YSHOP2-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-726 : themes > prevent opening cart drawer on cart page

- sections/product.liquid
- templates/product.json
[YSHOP2-719](https://youcanshop.atlassian.net/browse/YSHOP2-719)
[YSHOP2-719]: https://youcanshop.atlassian.net/browse/YSHOP2-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-719 : fix schema settings for express checkout and add to cart

- templates/index.json
[YSHOP2-733](https://youcanshop.atlassian.net/browse/YSHOP2-733)
[YSHOP2-733]: https://youcanshop.atlassian.net/browse/YSHOP2-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-733: Default theme settings - theme 3

- assets/main.css
- assets/notice-bar.css
- config/settings_data.json
- sections/notice-bar.liquid
- styles/main.scss
- styles/notice-bar.scss
[YSHOP2-873](https://youcanshop.atlassian.net/browse/YSHOP2-873)
[YSHOP2-873]: https://youcanshop.atlassian.net/browse/YSHOP2-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-873: Notice bar

- assets/featured-products.css
- assets/main.css
- locales/ar.default.json
- locales/en.json
- locales/fr.json
- sections/feature-products-by-category.liquid
- snippets/product-preview.liquid
- styles/featured-products.scss
- styles/main.scss
[YSHOP2-892](https://youcanshop.atlassian.net/browse/YSHOP2-892)
[YSHOP2-892]: https://youcanshop.atlassian.net/browse/YSHOP2-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Products by category

- sections/multi-column.liquid
[YSHOP2-886](https://youcanshop.atlassian.net/browse/YSHOP2-886)
[YSHOP2-886]: https://youcanshop.atlassian.net/browse/YSHOP2-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-886 : Multi column

- assets/footer.css
- assets/main.css
- config/settings_data.json
- sections/main-footer.liquid
- styles/footer.scss
[YSHOP2-882](https://youcanshop.atlassian.net/browse/YSHOP2-882)
[YSHOP2-882]: https://youcanshop.atlassian.net/browse/YSHOP2-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-882: Update footer styles and settings

- assets/featured-collections.css
- sections/featured-collections.liquid
- styles/featured-collections.scss
[YSHOP2-895](https://youcanshop.atlassian.net/browse/YSHOP2-895)
[YSHOP2-895]: https://youcanshop.atlassian.net/browse/YSHOP2-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-895: Featured Collections

- assets/desktop-slider.css
- assets/mobile-slider.css
- sections/desktop-slider.liquid
- snippets/slider.liquid
- styles/desktop-slider.scss
- styles/mobile-slider.scss
- templates/index.json
[YSHOP2-884](https://youcanshop.atlassian.net/browse/YSHOP2-884)
[YSHOP2-884]: https://youcanshop.atlassian.net/browse/YSHOP2-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-884 : theme 3 > Slider

- assets/video.css
- sections/main-video.liquid
- styles/video.scss
[YSHOP2-901](https://youcanshop.atlassian.net/browse/YSHOP2-901)
[YSHOP2-901]: https://youcanshop.atlassian.net/browse/YSHOP2-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-901 : theme 3 > video

- assets/add-to-cart.js
- assets/cart-drawer.css
- locales/ar.default.json
- styles/cart-drawer.scss
[YSHOP2-903](https://youcanshop.atlassian.net/browse/YSHOP2-903)
[YSHOP2-903]: https://youcanshop.atlassian.net/browse/YSHOP2-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-903: Cart drawer

- assets/main.css
- sections/product.liquid
- snippets/add-to-cart.liquid
- styles/main.scss
- templates/product.json
[YSHOP2-919](https://youcanshop.atlassian.net/browse/YSHOP2-919)
[YSHOP2-919]: https://youcanshop.atlassian.net/browse/YSHOP2-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-919: Update add to cart in single product page

- assets/countdown.css
- assets/product.css
- sections/product.liquid
- styles/countdown.scss
- styles/product.scss
- templates/product.json
[YSHOP2-917](https://youcanshop.atlassian.net/browse/YSHOP2-917)
[YSHOP2-917]: https://youcanshop.atlassian.net/browse/YSHOP2-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-917: Stock & Countdown timer

- assets/collection-listing.css
- assets/featured-collections.css
- sections/featured-collections.liquid
- sections/main-list-collections.liquid
- snippets/collection-preview.liquid
- styles/collection-listing.scss
- styles/featured-collections.scss
[YSHOP2-921](https://youcanshop.atlassian.net/browse/YSHOP2-921)
[YSHOP2-921]: https://youcanshop.atlassian.net/browse/YSHOP2-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-921: Collections page

- assets/cart.css
- assets/cart.js
- assets/main.css
- sections/main-cart.liquid
- styles/cart.scss
- styles/main.scss
[YSHOP2-902](https://youcanshop.atlassian.net/browse/YSHOP2-902)
[YSHOP2-902]: https://youcanshop.atlassian.net/browse/YSHOP2-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-902 : theme 3 > Cart page

- assets/add-to-cart.js
[YSHOP2-988](https://youcanshop.atlassian.net/browse/YSHOP2-988)
[YSHOP2-988]: https://youcanshop.atlassian.net/browse/YSHOP2-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-988: fix add to cart loader

- assets/express-checkout.css
- assets/product.css
- assets/product.js
- snippets/express-checkout.liquid
- snippets/single-product.liquid
- styles/express-checkout.scss
- styles/product.scss
[YSHOP2-986](https://youcanshop.atlassian.net/browse/YSHOP2-986)
Issues are described in the ticket with screenshots
[YSHOP2-986]: https://youcanshop.atlassian.net/browse/YSHOP2-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-986: theme 3  > Themes bugs for (single product section & navbar section)

- assets/cart.css
- assets/cart.js
- locales/ar.default.json
- locales/en.json
- locales/fr.json
- sections/main-cart.liquid
- styles/cart.scss
[YSHOP2-660](https://youcanshop.atlassian.net/browse/YSHOP2-660)
[YSHOP2-660]: https://youcanshop.atlassian.net/browse/YSHOP2-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-660: Can't see the applied coupon on new themes

- assets/upsell.css
- sections/main-upsell.liquid
- styles/upsell.scss
-  [ ] check the upsell page from theme editor
> DARK : theme 3 > fix upsell page styling

- assets/navbar.css
- styles/navbar.scss
[slack thread](https://youcan-shop.slack.com/archives/C04CW1478R1/p1699002494075309)
> DARK : Fix the navbar logo height

- assets/dropdown-menu.js
- assets/queries-handler.js
- snippets/product-variants.liquid
[YSHOP2-1031](https://youcanshop.atlassian.net/browse/YSHOP2-1031)
[YSHOP2-1031]: https://youcanshop.atlassian.net/browse/YSHOP2-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-1031: COD themes > theme 3 > dropdown menu bugs

- assets/featured-products.css
- styles/featured-products.scss
[YSHOP2-1038](https://youcanshop.atlassian.net/browse/YSHOP2-1038)
[YSHOP2-1038]: https://youcanshop.atlassian.net/browse/YSHOP2-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-1038: Featured products title position issue

- assets/navbar.css
- styles/navbar.scss
[Thread link](https://youcan-shop.slack.com/archives/C04CW1478R1/p1699376415433779)
> DARK: Fix the navbar background color

- snippets/product-preview.liquid
- snippets/product-slider.liquid
[YSHOP2-1025](https://youcanshop.atlassian.net/browse/YSHOP2-1025)
Direct add to cart not enabled: 
- Clicking anywhere in the block should redirect to that product page
Direct add to cart enabled:
- Clicking on the button leads to the norma behaviour of adding to cart (drawer appears)
- Clicking above the button redirects to that product page
[YSHOP2-1025]: https://youcanshop.atlassian.net/browse/YSHOP2-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-1025: Products listed should be clickable

- assets/express-checkout.js
[Thread link](https://youcan-shop.slack.com/archives/C04CW1478R1/p1700467656598849)
> DARK: Express checkout display error message

- assets/reviews.css
- sections/thankyou.liquid
- styles/reviews.scss
[thread 1](https://youcan-shop.slack.com/archives/C04CW1478R1/p1701420638492819)
[thread 2](https://youcan-shop.slack.com/archives/C04CW1478R1/p1701171113947219)
> DARK: Fix thank u page product url link

- assets/product-slider.css
- styles/product-slider.scss
[YSHOP2-1257](https://youcanshop.atlassian.net/browse/YSHOP2-1257)
[YSHOP2-1257]: https://youcanshop.atlassian.net/browse/YSHOP2-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-1257: Themes : Reviews section title display 

- assets/express-checkout.css
- assets/express-checkout.js
- assets/main.css
- snippets/express-checkout.liquid
- styles/express-checkout.scss
- styles/main.scss
[YSHOP2-1372](https://youcanshop.atlassian.net/browse/YSHOP2-1372)
-  go to settings > payment and add a custom field
- try to add different types of fields 
- then verify that the custom fields it's appear on the theme
[YSHOP2-1372]: https://youcanshop.atlassian.net/browse/YSHOP2-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> YSHOP2-1372: Add the option to display the states as a drop-down list on the new themes

- assets/main.js
- layouts/theme.liquid
[SHOP-1497](https://youcanshop.atlassian.net/browse/SHOP-1497)
[SHOP-1497]: https://youcanshop.atlassian.net/browse/SHOP-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SHOP-1497 : Display error message when total cart amount is greater than max checkout amount

- assets/express-checkout.js
- assets/main.css
- snippets/express-checkout.liquid
- styles/main.scss
[SHOP-1372](https://youcanshop.atlassian.net/browse/SHOP-1372)
[SHOP-1372]: https://youcanshop.atlassian.net/browse/SHOP-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SHOP-1372: [Meraki] Add the option to display the states as a drop-down list on the new themes
